### ISSUE TITLE
combine_obs_healpix needs updating

### ISSUE THREAD

**Issue by adampbeardsley** [miguelfmorales/FHD#10]
combine_obs_healpix needs to be updated to conform to the new file structure.
combein_obs_hpx_image will probably need updating too.

**Comment by piyanatk** [comment]
What is the problem with Stokes parameters conversion? Running on v3.0-325-gb345644, FHD produces combined healpix cubes of stokes I and Q if using 2 polarizations. This seems to be correct.

**Comment by isullivan** [comment]
Combine_obs_healpix produces "Stokes" images by simply adding or subtracting the instrumental xx and yy (and xy, yx) images after correcting for the primary beam. The correct approach is to calculate the Jones matrix for each pixel to perform a proper rotation. I expect this issue to be corrected soon.

**Comment by isullivan** [comment]
This was fixed back when version 3.5 was released. Closing now.
