### ISSUE TITLE
Converting FHD FITS output from Jy/beam to Kelvin

### ISSUE THREAD

**Issue by piyanatk** [miguelfmorales/FHD#19]
Is there a way to get the beam size that FHD use? I need to convert the output FITS images from Jy/beam to kelvin. I see that there is a RES parameter in the setting file. Is that the synthesize beam resolution in arcminute? Perhaps, this information should be in the FITS keywords.

**Comment by isullivan** [comment]
Within IDL, you can get the gaussian approximation of the beam width using the function synth_beam_width=beam_width_calculate(obs) . The return value is in pixels. Set either /degree to return the width in degrees or /radians to return the width in radians. You can also set the keyword /fwhm to instead return the full width half max of the gaussian approximation in any of those units.

Which value (fwhm or gaussian width) and which units do you want in the FITS header, and what name do you want it entered with?

**Comment by piyanatk** [comment]
Thanks Ian. Normally, the beam information is recorded as BMAJ, BMIN and BPA as floating point values in degrees. The BMAJ and BMIN are FWHM of a the major and minor axis of the Gaussian restoring beam used in the deconvolution. BPA is the positional angle of the major axis measuring from North (up) counter clockwise. If FHD use a Gaussian synthesize beam in the deconvolution, then we should stick to the standard.

What is the obs input parameter?

**Comment by isullivan** [comment]
The Gaussian approximation is used to estimate the area of the synthesized beam for converting the output residual image from Jy/pixels to Jy. It is not used internally or for deconvolution (where the 'true' synthesized beam is used), so we really have some flexibility how we calculate and use this value. 

The 'obs' input parameter is the obs data structure saved as metadata\*_obs.sav that contains most of the observation parameters and astrometry and is used extensively throughout FHD. It contains nested pointers and structures, so you may not be able to recover it easily in Python or otherwise outside of IDL.

**Comment by piyanatk** [comment]
I think we should store the Gaussian beam information as BMAJ, BMIN and BPA keywords and put your first first paragraph in a COMMENT keyword then if we still want to keep the flux unit as Jy/beam.

There is a spicy.io.readsave routine which seems to read IDL structure into Python dictionary. Also, I remember that Danny mentioned that someone in MWA team already wrote a script to do that. I will try these and report back.

**Comment by piyanatk** [comment]
@isullivan How do I read *_obs.sav files in IDL? I try read_binary, but it read the file as byte stream instead.

**Comment by isullivan** [comment]
The FHD *.sav files are the built-in save format of IDL, so use restore,'path\to\file.sav'

**Comment by piyanatk** [comment]
Thanks Ian. I was able to calculate the beam width from the *obs.sav files fine from within Python. :D

When you convert the residual image from Jy/pixels to Jy/beam, did you use this equation to get the pixel/beam factor?

Omega_A = (pi * theta_FWHM ^ 2) / (4 * ln(2)) 

Just making sure that I am reverting the calculation correctly.

Also one strength things I see is that sometimes the beam width increases as the frequency increases (as supposed to be the opposite). I have identify these frequencies to be:

    array([ 140.755,  144.195,  144.275,  145.395,  147.715,  154.595,
        155.875,  158.755,  160.515,  164.195,  165.875,  167.075,
        168.995,  170.115,  172.275,  173.555,  173.795,  175.475,
        176.435,  177.475,  178.115,  180.035,  181.395,  182.275,
        184.515,  186.275,  189.155,  189.235,  192.115]

In my calculation, each frequency channel is a separate simulation of a zenith drift scan with 2 second integration and 80kHz channel width, so they are pointing at approximately the same altitude and azimuth. The beam shape should be approximately the same but just decreases in size as frequency increases, I believe. Pleas see this [gist](https://gist.github.com/piyanatk/a547dc3178126da93b7f) for a full beam width table.

-Boom=

**Comment by piyanatk** [comment]
@isullivan Is the beam area calculation correct in beam_width_calculate? I got:
    IDL> beam_width_calculate(obs)                       
          0.61592031
    IDL> beam_width_calculate(obs, /area_return)
           6.6086750
   IDL> !PI * 0.61592031 * 0.61592031 / (4. * Alog(2.))
          0.42984655

**Comment by piyanatk** [comment]
@isullivan what is the beam threshold that you used to crop the FITS output?

**Comment by piyanatk** [comment]
It looks like I just did not understand IDL syntax in the previous post. beam_width_calculate work as expected.

Renaming and closing this case for future reference.
