### ISSUE TITLE
Error in healpix_snapshot_cube_generate when not using split_ps_export

### ISSUE THREAD

**Issue by adampbeardsley** [miguelfmorales/FHD#20]
I got the following error when trying to run healpix_snapshot_cube_generate without setting split_ps_export:
% LINDGEN: Variable is undefined: NB.
% Execution halted at: HEALPIX_SNAPSHOT_CUBE_GENERATE   90
   /nfs/eor-00/h1/beards/MWA/IDL_code/FHD/fhd_output/healpix_snapshot_cube_generate.pro

I can't see where nb was meant to be defined, so I assume it was meant to be defined elsewhere but some kind of versioning broke it.

Run is on the MIT machines at: /nfs/mwa-03/r1/EoR2014/fhd_apb_look_for_variable_2

**Comment by isullivan** [comment]
Fixed in master: v3.0-13-g006548f
