### ISSUE TITLE
Incorrect CRPIX Keyword in UV Weight FITS Output

### ISSUE THREAD

**Issue by piyanatk** [miguelfmorales/FHD#22]
It seems that size of UV weight images is always half of the primary beam and intensity images, but the reference pixels of the former are set to be the same as the reference pixels of the later. This makes the reference pixels fall outside of the images as supposed to be at the center.
Please see /data4/piyanat/fhd_images/test on ASU enterprise.

**Comment by isullivan** [comment]
The UV weight FITS image header has been modified to include parameters relevant to u-v space.
