### ISSUE TITLE
Sidelobe subtraction before deconvolution

### ISSUE THREAD

**Issue by nicholebarry** [miguelfmorales/FHD#34]
Sidelobe subtraction before deconvolution did not produce errors, but did produce weird results. The directory where it is located is /nfs/mwa-09/r1/djc/EoR2013/Aug23/fhd_nb_decon_Nov2015_presidelobesubtract/. Below is the 2d power spectra for that test, and below that is the fhd_nb_decon_Nov2015 (normal decon) for comparison purposes.
![fhd_nb_decon_nov2015_presidelobesubtract_aug23_bh_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11359926/43b0657a-9235-11e5-97d5-0f28f9f7e715.png)
![fhd_nb_decon_nov2015_aug23_bh_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11359931/4b49aee0-9235-11e5-9ab2-aa277a706f45.png)

**Comment by isullivan** [comment]
I believe this is now fixed. The bug was that sources near the edge of the image were aliasing in to the center of the FoV.
