### ISSUE TITLE
Negative flux_threshold and negative apparant brightness cut (my hack) reveals weird behavior

### ISSUE THREAD

**Issue by nicholebarry** [miguelfmorales/FHD#37]
Ian made an option for inputting a negative flux threshold, which would cut the *bright* sources instead of the normal option which would cut the *faint* sources. This has revealed interesting behavior...

1) The number of sources in each source list does not match the total number of possible source in the known catalog for a cut on flux. (Note, I usually use a cut on apparent brightness, not a cut on Stokes I flux, so the numbers might be different than what you're used to hearing from me). Negative cut, keep all sources below 0.3Jy: 1604 sources. Positive cut, keep all source above 0.3Jy: 5393 sources. Total from the two cuts: 6997. Total number of sources in catalog: 6995. PS for this test is uncomparable due to inclusion of diffuse.

2) The number of sources in each source list does not match the total number of possible source in the known catalog for a cut on apparant brightness. Negative cut, keep faint sources below brightest 4000: 2997 sources. Positive cut, keep brightest 4000 sources: 4000 sources. Total from the two cuts: 6997. Total number of sources in catalog: 6995. PS for this test is uncomparable due to inclusion of diffuse.

I'm going to work on running a new test without diffuse so PS are comparable. The difference in the source list is weird though.

/nfs/mwa-09/r1/djc/EoR2013/Aug23/fhd_nb_sim_perfect_cal_beamperchannel_novisflagbasic_modelnoflag_eor_weightfix_ones_dimcalsources/

/nfs/mwa-09/r1/djc/EoR2013/Aug23/fhd_nb_sim_perfect_cal_beamperchannel_novisflagbasic_modelnoflag_eor_weightfix_ones_dimfluxthreshold/

**Comment by nicholebarry** [comment]
Here is a difference test that might help. I'll explain each constituent.

1) Residual of a 6995 input model, but calibrating and subtracting only the brightest 4000. No diffuse involved. Perfect calibration.

2) Model of a the remaining sources after 4000 of the brightest were cut. Metadata said this was 2950 sources (which appears to add to the source list problem, since that number should be 2995). No diffuse involved. Perfect calibration. Noteworthy: substantially more flagged tiles (16). Can transfer flags in a future test to avoid this.

The difference is thus case 1 minus case 2. Theoretically, they should be the same. I'm not sure how much contribution the extra flagged tiles would have had. However, I'm still perplexed about the difference in source lists! I did some quick sorting, and couldn't seem to find a matching source in the source lists made in my first comment, which one would expect since there is more than the allotted number of total input sources. I don't think we can really make comparisons in PS until we sort this out.

![fhd_nb_sim_perfect_cal_eor_ones_nod__maxcalsources_res_xx_minus_dimcalsources_model_xx_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11708650/dfa1c3b0-9ec5-11e5-94f0-f79b5911ee41.png)

**Comment by bhazelton** [comment]
The source list problem definitely has to be sorted out first, but the blue
in the window is very interesting. Have you looked at the image cubes?
Differencing the cubes might show the source differences.

**Comment by nicholebarry** [comment]
Upon further inspection, I think I understand what is going on. I think the refraction correction that was implemented a few weeks ago has changed which sources fall out of the beam. This may have been implemented halfway through the runs of case 1 and case 2 (described above). However, it was implemented through the last two runs that were used for the above difference test, and the total source of 6950 is correct.

So, this means there is a significant difference when there should be none. I'll take a look at image cubes.

**Comment by nicholebarry** [comment]
Mostly based off of a confusion between a refraction correction being applied to a simulation but not the model.
