### ISSUE TITLE
Deconvolution only finds 4 sources!

### ISSUE THREAD

**Issue by nicholebarry** [miguelfmorales/FHD#42]
I recently ran a full night of deconvolution using the master branch with code version 4b5d663. It ran fully with no errors, yet it seems that it only found 4 to 5 sources during deconvolution. The specific keywords set where:
      max_sources=200000
      gain_factor=0.1
      deconvolve=1
      return_decon_visibilities=1
      smooth_width=32
      deconvolution_filter='filter_uv_uniform'
      filter_background=1
      dimension=3072
      return_cal_visibilities=0
      FoV=0
      pad_uv_image=1
      snapshot_healpix_export=1
      recalculate_all=1
Here are the sources that were picked out presented in a model image. There doesn't seem to be a quadrant preference.
![1061311664_uniform_model_xx](https://cloud.githubusercontent.com/assets/5588290/13408517/150e4a48-dee3-11e5-9ecb-64ec48d29ed2.png)

Here is the settings file and output log.
[1061311664_settings.txt](https://github.com/miguelfmorales/FHD/files/151727/1061311664_settings.txt)
[firstpass.o67540.1.txt](https://github.com/miguelfmorales/FHD/files/151729/firstpass.o67540.1.txt)

Let me know if there is anything else I can provide.

**Comment by isullivan** [comment]
I've confirmed that this is an overflow bug in fast_dft, which is used internally in deconvolution. I'm working on a fix, and will close this issue once that's pushed.

**Comment by bhazelton** [comment]
Good hunting!

**Comment by isullivan** [comment]
Fixed on master in v3.5-152-gee509cb
